language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
    - /.*/

before_script:
  - cd src && npm install
  - npm i -g codecov

script:
  - ng test ngx-responsivemenu --watch=false
  - codecov